In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Data/rawdata/high_beta/ADSK.csv')

In [5]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2007-11-01,48.160000,49.000000,47.730000,47.799999,47.799999,1871100
1,2007-11-02,48.369999,48.939999,47.480000,48.810001,48.810001,1671500
2,2007-11-05,48.150002,48.540001,47.790001,48.099998,48.099998,1574900
3,2007-11-06,49.680000,49.730000,48.650002,49.709999,49.709999,2448700
4,2007-11-07,49.380001,49.840000,48.369999,48.419998,48.419998,1875800
5,2007-11-08,48.200001,48.549999,45.500000,47.360001,47.360001,3746500
6,2007-11-09,46.509998,47.259998,46.020000,46.160000,46.160000,2479600
7,2007-11-12,46.020000,46.669998,44.840000,44.840000,44.840000,3080400
8,2007-11-13,46.660000,48.599998,44.840000,47.990002,47.990002,3299500
9,2007-11-14,48.630001,49.000000,47.500000,47.529999,47.529999,2579700
10,2007-11-15,47.279999,48.000000,46.840000,47.459999,47.459999,2821600
11,2007-11-16,44.869999,47.459999,44.779999,46.410000,46.410000,6011300
12,2007-11-19,46.310001,46.689999,45.700001,46.070000,46.070000,2897100
13,2007-11-20,46.139999,47.209999,45.250000,46.340000,46.340000,1796200
14,2007-11-21,46.290001,47.180000,44.900002,45.230000,45.230000,2509500
15,2007-11-23,45.340000,46.150002,45.250000,45.790001,45.790001,639200
16,2007-11-26,45.369999,46.130001,44.509998,44.560001,44.560001,1689200
17,2007-11-27,44.950001,46.529999,44.599998,45.869999,45.869999,2505900
18,2007-11-28,45.900002,46.799999,45.349998,46.619999,46.619999,3532100
19,2007-11-29,46.459999,47.639999,46.180000,47.459999,47.459999,1925500
20,2007-11-30,47.419998,47.830002,46.830002,47.090000,47.090000,2218500
21,2007-12-03,46.759998,47.950001,46.689999,47.529999,47.529999,2394200
22,2007-12-04,46.840000,47.950001,46.840000,47.590000,47.590000,1410900
23,2007-12-05,47.980000,49.209999,47.849998,48.720001,48.720001,2277400
24,2007-12-06,48.910000,48.910000,47.400002,48.090000,48.090000,3183300
25,2007-12-07,48.000000,48.369999,47.439999,48.200001,48.200001,1587200
26,2007-12-10,48.639999,49.950001,48.509998,49.680000,49.680000,1852500
27,2007-12-11,49.330002,50.180000,49.000000,49.099998,49.099998,2791100
28,2007-12-12,49.970001,50.130001,49.000000,49.500000,49.500000,2452900
29,2007-12-13,49.400002,50.470001,49.209999,50.330002,50.330002,2125800
...,...,...,...,...,...,...,...
2489,2017-09-21,112.820000,113.000000,111.370003,112.290001,112.290001,1154500
2490,2017-09-22,111.680000,112.820000,111.639999,111.779999,111.779999,1085000
2491,2017-09-25,111.669998,111.830002,108.650002,109.820000,109.820000,2026000
2492,2017-09-26,110.589996,111.379997,108.830002,110.610001,110.610001,1590500
2493,2017-09-27,110.209999,113.470001,110.209999,111.959999,111.959999,1731400
2494,2017-09-28,111.400002,111.959999,110.519997,111.449997,111.449997,1358300
2495,2017-09-29,111.250000,112.760002,111.000000,112.260002,112.260002,2033100
2496,2017-10-02,110.690002,113.760002,110.680000,112.470001,112.470001,1961300
2497,2017-10-03,112.389999,113.730003,111.669998,113.629997,113.629997,1044800
2498,2017-10-04,113.790001,114.070000,112.349998,114.050003,114.050003,1122300
2499,2017-10-05,114.500000,116.830002,113.900002,116.540001,116.540001,1673800
2500,2017-10-06,116.180000,117.610001,115.809998,116.959999,116.959999,1806200
2501,2017-10-09,116.800003,117.519997,116.639999,117.139999,117.139999,847100
2502,2017-10-10,117.220001,117.529999,116.320000,117.050003,117.050003,931500
2503,2017-10-11,117.019997,118.660004,116.930000,118.570000,118.570000,1078400
2504,2017-10-12,118.550003,119.839996,118.510002,118.989998,118.989998,1236600
2505,2017-10-13,119.769997,119.769997,118.449997,119.629997,119.629997,1262900
2506,2017-10-16,119.690002,119.970001,118.669998,119.199997,119.199997,1179600
2507,2017-10-17,119.349998,119.760002,118.059998,118.720001,118.720001,1184700
2508,2017-10-18,118.500000,118.860001,117.779999,118.540001,118.540001,1010600
2509,2017-10-19,119.000000,119.320000,117.570000,119.290001,119.290001,1099300
2510,2017-10-20,119.980003,121.879997,119.699997,120.809998,120.809998,1647600
2511,2017-10-23,120.989998,121.720001,118.730003,118.989998,118.989998,1487500
2512,2017-10-24,118.959999,119.610001,117.900002,119.290001,119.290001,1337800
2513,2017-10-25,119.000000,120.250000,118.050003,119.940002,119.940002,1080000
2514,2017-10-26,120.209999,121.949997,119.459999,121.349998,121.349998,902700
2515,2017-10-27,121.610001,123.970001,121.400002,123.580002,123.580002,1523700
2516,2017-10-30,123.040001,124.279999,121.900002,123.910004,123.910004,1610500
2517,2017-10-31,124.279999,125.010002,123.419998,124.959999,124.959999,1839900
2518,2017-11-01,125.629997,126.440002,123.400002,124.779999,124.779999,1622800

In [6]:
df2 = pd.read_csv('Data/rawdata/high_beta/ARNC.csv')

In [7]:
df2

,Date,Open,High,Low,Close,Adj Close,Volume
0,2007-11-01,88.178413,88.178413,84.872566,85.232384,74.607140,4821800
1,2007-11-02,85.817093,86.806595,84.512741,86.716644,75.906349,5859000
2,2007-11-05,84.670166,86.019493,84.377808,85.232384,74.607140,3679000
3,2007-11-06,85.299850,87.323837,85.299850,86.739128,75.926048,3198100
4,2007-11-07,85.907043,86.266869,83.905548,84.107948,73.622879,3298300
5,2007-11-08,87.706146,88.493256,82.826088,84.692657,74.134682,8978300
6,2007-11-09,84.512741,85.029984,81.656670,83.410797,73.012627,6238900
7,2007-11-12,83.095955,84.670166,80.262367,80.667168,70.611015,6541800
8,2007-11-13,81.184410,83.230888,80.734634,82.376312,72.107109,6627800
9,2007-11-14,83.230888,84.197899,82.398804,82.893555,72.559853,4849300
10,2007-11-15,82.398804,83.388306,81.341827,81.701653,71.516541,4752300
11,2007-11-16,82.083961,82.196404,78.328339,81.656670,71.477196,4873500
12,2007-11-19,80.982010,80.982010,78.283356,78.868065,69.036217,4525300
13,2007-11-20,78.935532,81.049477,78.350822,79.565216,69.646416,6925700
14,2007-11-21,78.890556,80.689651,77.721138,79.092957,69.233063,4095200
15,2007-11-23,79.452774,80.194901,78.283356,79.047974,69.193665,2105700
16,2007-11-26,79.227882,81.184410,78.440781,78.440781,68.662193,3810800
17,2007-11-27,78.688156,79.160423,77.631187,78.800598,68.977150,4794100
18,2007-11-28,79.452774,81.656670,79.272865,81.431786,71.280289,5271000
19,2007-11-29,80.959518,83.095955,80.554726,82.196404,71.949593,3802800
20,2007-11-30,83.005997,83.883057,80.959518,81.791603,71.595276,4682700
21,2007-12-03,82.038979,82.196404,79.587708,79.812592,69.862961,3593200
22,2007-12-04,79.182907,79.700150,78.395805,79.272865,69.390533,3510600
23,2007-12-05,79.857574,80.082458,78.890556,80.082458,70.099182,4267400
24,2007-12-06,80.059967,80.847076,79.475266,80.644676,70.591331,2845900
25,2007-12-07,80.104950,83.208397,80.104950,83.005997,72.658295,4111700
26,2007-12-10,83.410797,85.389809,83.208397,85.119942,74.508698,3332900
27,2007-12-11,84.467766,85.412292,80.802101,81.251877,71.122818,3956600
28,2007-12-12,82.916039,84.287857,81.544228,82.938530,72.599243,3958900
29,2007-12-13,82.218887,82.308846,79.587708,81.701653,71.516541,3447900
...,...,...,...,...,...,...,...
2476,2017-09-01,25.549999,25.780001,25.500000,25.510000,25.510000,2925100
2477,2017-09-05,25.480000,25.480000,24.200001,24.389999,24.389999,5200300
2478,2017-09-06,24.500000,24.799999,24.320000,24.340000,24.340000,4584700
2479,2017-09-07,24.389999,24.450001,24.110001,24.260000,24.260000,2492200
2480,2017-09-08,24.230000,24.500000,24.010000,24.420000,24.420000,4176900
2481,2017-09-11,24.570000,25.180000,24.549999,24.980000,24.980000,3091900
2482,2017-09-12,25.040001,25.209999,24.969999,25.160000,25.160000,1941100
2483,2017-09-13,25.160000,25.420000,24.980000,25.250000,25.250000,2281100
2484,2017-09-14,25.129999,25.440001,24.879999,25.360001,25.360001,2377200
2485,2017-09-15,25.370001,25.500000,25.150000,25.340000,25.340000,10943500
2486,2017-09-18,25.379999,25.490000,25.209999,25.340000,25.340000,1899900
2487,2017-09-19,25.350000,25.959999,25.160000,25.940001,25.940001,4252700
2488,2017-09-20,25.950001,26.200001,25.770000,26.200001,26.200001,3045400
2489,2017-09-21,26.190001,26.840000,25.959999,26.790001,26.790001,3813500
2490,2017-09-22,26.600000,26.750000,26.100000,26.209999,26.209999,3748100
2491,2017-09-25,26.209999,26.490000,25.860001,26.129999,26.129999,4532800
2492,2017-09-26,26.270000,26.350000,26.080000,26.270000,26.270000,3388400
2493,2017-09-27,26.450001,26.559999,26.080000,26.379999,26.379999,2927600
2494,2017-09-28,26.379999,26.379999,26.010000,26.020000,26.020000,1947100
2495,2017-09-29,26.040001,26.040001,24.549999,24.879999,24.879999,8422300
2496,2017-10-02,24.950001,25.920000,24.930000,25.920000,25.920000,5674500
2497,2017-10-03,25.840000,26.559999,25.740000,26.129999,26.129999,6068700
2498,2017-10-04,26.150000,26.879999,26.150000,26.770000,26.770000,3888100
2499,2017-10-05,26.650000,27.100000,26.650000,26.850000,26.850000,3655500
2500,2017-10-06,26.680000,27.150000,26.540001,27.100000,27.100000,2812100
2501,2017-10-09,27.170000,27.650000,27.110001,27.389999,27.389999,3748700
2502,2017-10-10,27.639999,27.850000,27.280001,27.389999,27.389999,2550100
2503,2017-10-11,27.280001,27.840000,27.120001,27.350000,27.350000,6910500
2504,2017-10-12,27.270000,27.690001,27.080000,27.559999,27.559999,3622100
2505,2017-10-13,27.670000,27.680000,27.040001,27.160000,27.160000,8723300

In [8]:
df.set_index('Date').join(df2.set_index('Date'))

ValueError: columns overlap but no suffix specified: Index([u'Open', u'High', u'Low', u'Close', u'Adj Close', u'Volume'], dtype='object')